# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Usuario:
           algorithm: bcrypt
           cost: 6

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_db_provider:
            entity:
                class: AppBundle:Usuario
                property: email

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ENCARGADO]   #Rol que se esta configurando: [Rol que está por debajo en la jerarquía]
        ROLE_ENCARGADO: [ROLE_EMPLEADO]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/(entrar|restablecer)
            security: false

        main:
            anonymous: ~
            provider: user_db_provider
            form_login:
                login_path: entrar
                check_path: comprobar
            logout:
                path: salir
                target: entrar

                # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~